import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Audit, AuditItem } from "./api";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const RESULT_STYLE: Record<string, { label: string; color: string; bg: string }> = {
  pass: { label: "PASS", color: "#1e7d45", bg: "#e6f4ec" },
  fail: { label: "FAIL", color: "#b03030", bg: "#fbeaea" },
  na: { label: "N/A", color: "#666666", bg: "#efefef" },
};

export function buildAuditHtml(audit: Audit): string {
  const sections: { name: string; items: AuditItem[] }[] = [];
  for (const it of audit.items) {
    let s = sections.find((x) => x.name === it.section);
    if (!s) { s = { name: it.section, items: [] }; sections.push(s); }
    s.items.push(it);
  }

  const scoreColor = audit.score == null ? "#666" : audit.score >= 85 ? "#1e7d45" : audit.score >= 60 ? "#a97b12" : "#b03030";
  const date = audit.completed_at ? new Date(audit.completed_at).toLocaleString() : "";

  const sectionHtml = sections.map((sec) => `
    <h3 class="section">${esc(sec.name)}</h3>
    ${sec.items.map((it) => {
      const r = RESULT_STYLE[it.result || ""] || { label: "—", color: "#999", bg: "#f5f5f5" };
      return `
      <div class="item">
        <div class="item-row">
          <span class="pill" style="color:${r.color};background:${r.bg}">${r.label}</span>
          <span class="item-text">${esc(it.text)}</span>
        </div>
        ${it.note ? `<div class="note">Note: ${esc(it.note)}</div>` : ""}
        ${it.photo_base64 ? `<img class="photo" src="data:image/jpeg;base64,${it.photo_base64}" />` : ""}
      </div>`;
    }).join("")}
  `).join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color: #222; margin: 32px; }
  .band { border-bottom: 3px solid #D4AF37; padding-bottom: 16px; margin-bottom: 20px; }
  .kicker { font-size: 11px; letter-spacing: 3px; color: #a98b1f; }
  h1 { font-size: 26px; margin: 4px 0 6px; font-weight: normal; }
  .meta { font-size: 13px; color: #555; }
  .scorebox { float: right; text-align: center; border: 2px solid ${scoreColor}; border-radius: 50%; width: 72px; height: 72px; line-height: 1; padding-top: 14px; box-sizing: border-box; }
  .scoreval { font-size: 24px; color: ${scoreColor}; }
  .scorelabel { font-size: 9px; color: #777; letter-spacing: 1px; }
  h2 { font-size: 16px; letter-spacing: 1px; margin: 24px 0 8px; color: #a98b1f; text-transform: uppercase; }
  h3.section { font-size: 15px; margin: 18px 0 8px; border-bottom: 1px solid #e5e5e5; padding-bottom: 4px; }
  .summary { font-size: 13px; line-height: 1.7; white-space: pre-wrap; background: #faf7ee; border: 1px solid #eadfc0; border-radius: 8px; padding: 14px; }
  .item { margin-bottom: 10px; page-break-inside: avoid; }
  .item-row { display: flex; align-items: center; gap: 8px; }
  .pill { font-size: 10px; font-weight: bold; padding: 3px 8px; border-radius: 10px; white-space: nowrap; font-family: Arial, sans-serif; }
  .item-text { font-size: 13px; }
  .note { font-size: 12px; font-style: italic; color: #666; margin: 4px 0 0 52px; }
  .photo { display: block; margin: 6px 0 0 52px; max-width: 220px; border-radius: 6px; border: 1px solid #ddd; }
  .footer { margin-top: 32px; border-top: 1px solid #e5e5e5; padding-top: 10px; font-size: 11px; color: #999; }
</style>
</head>
<body>
  <div class="band">
    <div class="scorebox"><div class="scoreval">${audit.score != null ? Math.round(audit.score) : "—"}</div><div class="scorelabel">SCORE %</div></div>
    <div class="kicker">CITY PARK HOTEL — AUDIT REPORT</div>
    <h1>${esc(audit.template_name)}</h1>
    <div class="meta">
      Department: ${esc(audit.department)}
      ${audit.location ? ` &nbsp;·&nbsp; Location: ${esc(audit.location)}` : ""}
      &nbsp;·&nbsp; Auditor: ${esc(audit.auditor_name)}
      &nbsp;·&nbsp; Completed: ${esc(date)}
    </div>
  </div>
  ${audit.ai_summary ? `<h2>AI Report Summary</h2><div class="summary">${esc(audit.ai_summary)}</div>` : ""}
  <h2>Checklist Results</h2>
  ${sectionHtml}
  <div class="footer">Generated by CityPark Audit · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

export async function exportAuditPdf(audit: Audit): Promise<void> {
  const html = buildAuditHtml(audit);
  if (Platform.OS === "web") {
    // Web: open the system print dialog (user can save as PDF)
    await Print.printAsync({ html });
    return;
  }
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Share Audit Report" });
  }
}
